---
peers:
  - csrv1.lab
  - csrv3.lab
  - csrv4.lab

bgp_global:
    as_number: '65537'
    bgp:
      log_neighbor_changes: true
      router_id:
        address: 172.31.38.157
    neighbors:
    - log_neighbor_changes:
        set: true
      neighbor_address: 172.31.39.79
      remote_as: '65536'
    - log_neighbor_changes:
        set: true
      neighbor_address: 172.31.33.78
      remote_as: '65539'
    - log_neighbor_changes:
        set: true
      neighbor_address: 172.31.40.115
      remote_as: '65538'

bgp_address_family:
    address_family:
    - afi: ipv4
      neighbor:
      - activate: true
        address: 172.31.33.78
      - activate: true
        address: 172.31.39.79
      - activate: true
        address: 172.31.40.115
      network:
      - address: 198.51.100.0
      - address: 198.51.101.0
      - address: 198.51.102.0
    as_number: '65537'