---
- hosts: csrv3.lab
  gather_facts: false
  tasks:
    - cisco.ios.ios_config:
        lines:
          - "router bgp 65538"
          - "  address-family ipv4 unicast"
          - "    network 203.0.113.0"
    
    - pause:
        seconds: 10
