---
- hosts: all
  gather_facts: false
  tasks:
    - name: "CSRv - Configure BGP"
      cisco.ios.ios_bgp_global:
        config: "{{ bgp_global }}"
        state: replaced

    - name: "CSRv - Configure BGP Address Family"
      cisco.ios.ios_bgp_address_family:
        config: "{{ bgp_address_family }}"
        state: overridden
