---
- hosts: csrv1.lab
  gather_facts: false
  tasks:
    - name: Get and parse BGP operational state
      ansible.utils.cli_parse:
        command: show bgp neighbors
        parser:
          name: ansible.netcommon.pyats
      register: result

    - name: Validate BGP operational state
      ansible.utils.validate:
        data: "{{ result['parsed']['vrf']['default'] }}"
        criteria: "{{ lookup('file', '../schemas/{{ inventory_hostname }}_bgp.json') }}"
