---
- hosts: all
  gather_facts: false
  tasks:
    - ansible.builtin.command: pip show jsonschema

    - name: Get and parse BGP operational state
      ansible.utils.cli_parse:
        command: show bgp neighbors
        parser: 
          name: ansible.netcommon.pyats
      register: result
      retries: 5
      delay: 5
      until: ("BGP state = Established") in result.stdout

    - name: Validate BGP operational state
      ansible.utils.validate:
        data: "{{ result['parsed']['vrf']['default'] }}"
        criteria: "{{ lookup('file', '../schemas/{{ inventory_hostname }}_bgp.json') }}"
