---
- hosts: all
  gather_facts: false
  tasks:
    - name: Get CPU utilization
      ansible.utils.cli_parse:
        command: "show processes cpu"
        parser:
          name: ansible.netcommon.pyats
        set_fact: cpu_utilization

    - name: Verify that CPU utilization is within threshold
      ansible.builtin.assert:
        that:
          - cpu_utilization.five_min_cpu < 80
