---
- hosts: all
  gather_facts: no
  tasks:
    - name: Get and parse interface operational state
      ansible.utils.cli_parse:
        command: show ip interface
        parser: 
          name: ansible.netcommon.pyats
      register: result

    - name: Validate interface operational state
      ansible.utils.validate:
        data: "{{ result['parsed'] }}"
        criteria: "{{ lookup('file', '../schemas/interface.json') }}"